### PR TITLE
 Panic if SpinLock locked in interrupt context

### LINKED ISSUE #471: Detect usage of SpinLock in IRQ context
It'd be nice if we could detect use of a SpinLock in an IRQ context. Such usage would be wrong (since it might end up deadlocking the CPU). @Orycterope I wonder if we could set a global boolean or something in an IRQ, and check it when locking a SpinLock, panicking if it's set?

### PR DESCRIPTION
**Pull request by kitlith**
Fixes #471.

This involves creating a newtype wrapper around spin::Mutex to check when locking if the number of interrupts being serviced is currently zero.

### CODE REVIEW

**Comment by kitlith** [comment]
It looks like maybe I should fiddle with this a bit more *if* syscall context is not considered irq context. (Is it? It's the only 'interrupt' where interrupts are not disabled.) maybe add an extra thing to the macro?

**Comment by Orycterope** [comment]
Indeed, syscalls context isn't interrupt context 😕

File: kernel/src/sync/spin_lock.rs [hunk 1]
```diff
@@ -0,0 +1,156 @@
...
+    ///     let mut data = mylock.lock();
+    ///     // The lock is now locked and the data can be accessed
+    ///     *data += 1;
+    ///     // The lock is implicitly dropped
+    /// }
+    ///
+    /// ```
+    pub fn lock(&self) -> SpinLockGuard<T> {
+        use core::sync::atomic::Ordering;
+        assert_eq!(crate::i386::interrupt_service_routines::INSIDE_INTERRUPT_COUNT.load(Ordering::SeqCst), 0);
```
Comment (Orycterope) [inline kernel/src/sync/spin_lock.rs]: Add a verbose panic message telling the user it has a design flaw and should refer to the sync module documentation.

File: kernel/src/sync/spin_lock.rs [hunk 2]
```diff
@@ -0,0 +1,156 @@
...
+    ///
+    /// If the lock isn't held, this is a no-op.
+    pub unsafe fn force_unlock(&self) {
+        self.0.force_unlock()
+    }
+
+    /// Tries to lock the spinlock. If it is already locked, it will return None. Otherwise it returns
+    /// a guard within Some.
+    pub fn try_lock(&self) -> Option<SpinLockGuard<T>> {
+        self.0.try_lock()
```
Comment (Orycterope) [inline kernel/src/sync/spin_lock.rs]: `try_lock` should panic too. The user made a design flaw, be loud about it.

**Comment by kitlith** [comment]
Thanks for the feedback, I'll try to get to that today. Fixing syscall context in particular is going to be annoying (but that'll also lay the groundwork for switching back to counter-based SpinLockIRQ, i think.)

**Comment by roblabla** [comment]
LGTM, can get merged after a rebase :)
